from model import call_model

def build_judge_prompt(user_request: str, draft_story: str) -> tuple[str, str]:
    """
    Build the prompt for the 'judge' agent, which will improve or rewrite the story.
    
    Returns a tuple of (system_prompt, user_prompt).
    """
    system_prompt = """You are an editor and educator helping polish bedtime stories for children.

Audience: kids aged 5–10 who are about to sleep. The story will be read aloud by a parent.

Evaluate stories using the following checklist:
1. Is the language simple enough for ages 5–10?
2. Is the tone gentle and appropriate for bedtime (not too scary, sad, or intense)?
3. Is there a clear beginning, middle, and end?
4. Is the story coherent and easy to follow when read aloud?
5. Is there a positive, reassuring ending and a simple moral?

If a story does not meet all criteria, rewrite it from start to finish so that it satisfies all criteria,
while staying faithful to the original request and preserving the main characters
and themes as much as possible.

Output only the final improved bedtime story, with no additional commentary."""

    user_prompt = f"""Here is the original story request from the adult:
"{user_request}"

Here is a draft story generated by another model:

--- STORY START ---
{draft_story}
--- STORY END ---"""

    return (system_prompt, user_prompt)


def build_revision_prompt(user_request: str, current_story: str, feedback: str) -> tuple[str, str]:
    """
    Build a prompt that asks the model to revise the existing story according to the user's feedback.
    
    Returns a tuple of (system_prompt, user_prompt).
    """
    system_prompt = """You are revising a children's bedtime story based on feedback from the adult reader.

Audience: kids aged 5–10 who are about to go to sleep.

When revising a story, keep:
- the same main characters,
- the same general setting (unless the feedback says otherwise),
- the same gentle bedtime tone.

The story should still:
- be appropriate for ages 5–10,
- have a clear beginning, middle, and end,
- end in a comforting way with a simple moral.

Output only the revised story, with no additional commentary."""

    user_prompt = f"""Original request:
"{user_request}"

Current story:

--- STORY START ---
{current_story}
--- STORY END ---

Feedback from the adult about how to change the story:
"{feedback}"

Revise the story to address the feedback."""

    return (system_prompt, user_prompt)

def judge_and_improve_story(user_request: str, draft_story: str) -> str:
    """
    Use the judge prompt to evaluate and improve the draft story.
    """
    system_prompt, user_prompt = build_judge_prompt(user_request, draft_story)
    improved_story = call_model(system_prompt, user_prompt, max_tokens=1500, temperature=0.4)
    return improved_story


def revise_story(user_request: str, current_story: str, feedback: str) -> str:
    """
    Apply user feedback to revise the story.
    """
    system_prompt, user_prompt = build_revision_prompt(user_request, current_story, feedback)
    revised_story = call_model(system_prompt, user_prompt, max_tokens=1500, temperature=0.6)
    return revised_story